# Generated by Django 3.2.4 on 2021-06-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='社名')),
                ('owner', models.CharField(max_length=15, verbose_name='代表者')),
                ('business', models.CharField(max_length=63, verbose_name='事業内容')),
                ('tel', models.CharField(max_length=31, verbose_name='TEL')),
                ('fax', models.CharField(max_length=31, verbose_name='FAX')),
                ('email', models.EmailField(max_length=254, verbose_name='メール')),
                ('address', models.TextField(verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='クラフト名')),
                ('thumbnail', models.ImageField(upload_to='craft', verbose_name='サムネイル')),
                ('text', models.TextField(verbose_name='テキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='仕事名')),
                ('thumbnail', models.ImageField(upload_to='work', verbose_name='サムネイル')),
                ('text', models.TextField(verbose_name='テキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='画像名')),
                ('img', models.ImageField(upload_to='work', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.work')),
            ],
        ),
        migrations.CreateModel(
            name='CraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='画像名')),
                ('img', models.ImageField(upload_to='craft', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.craft')),
            ],
        ),
    ]
