# Generated by Django 3.2.4 on 2021-07-16 06:19

from django.db import migrations
import stdimage.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_work_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=stdimage.models.StdImageField(max_length=32, upload_to=website.models.set_work_img_name, verbose_name='サムネイル'),
        ),
    ]
