# Generated by Django 3.2.4 on 2021-07-16 06:34

from django.db import migrations
import stdimage.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_work_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craftimage',
            old_name='works',
            new_name='crafts',
        ),
        migrations.AlterField(
            model_name='craft',
            name='thumbnail',
            field=stdimage.models.StdImageField(max_length=32, upload_to=website.models.set_craft_img_name, verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='craftimage',
            name='img',
            field=stdimage.models.StdImageField(max_length=32, upload_to=website.models.set_craft_img_name, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='img',
            field=stdimage.models.StdImageField(max_length=32, upload_to=website.models.set_work_img_name, verbose_name='画像'),
        ),
    ]
