# Generated by Django 3.2.4 on 2021-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210716_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='タイトル')),
                ('send_by', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=31, verbose_name='TEL')),
                ('content', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
