# Generated by Django 3.2.4 on 2021-08-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='a', max_length=127, verbose_name='お名前'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(verbose_name='お問い合わせ内容'),
        ),
    ]
