# Generated by Django 3.2.4 on 2021-08-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210819_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '会社情報', 'verbose_name_plural': '会社情報'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'お問い合わせ', 'verbose_name_plural': 'お問い合わせ'},
        ),
        migrations.AlterModelOptions(
            name='craft',
            options={'verbose_name': 'Craft', 'verbose_name_plural': 'Craft'},
        ),
        migrations.AlterModelOptions(
            name='craftimage',
            options={'verbose_name': 'Craft画像', 'verbose_name_plural': 'Craft画像'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Work'},
        ),
        migrations.AlterModelOptions(
            name='workimage',
            options={'verbose_name': 'Work画像', 'verbose_name_plural': 'Work画像'},
        ),
    ]
